development:
  adapter: postgresql
  encoding: unicode
  database: makersbnb #likely need to change to makersbnb
  pool: 2

test:
  adapter: postgresql
  encoding: unicode
  database: makersbnb_test #also change potentially?
  pool: 2 